### PR TITLE
clean up dash between date range

### PR DESCRIPTION
**Pull request by zenahirsch**
This theme is great, but the date ranges are currently a little hard to read:

2010-07-01-2011-12-16

I think some spacing and an emdash will help:

2010-07-01 — 2011-12-16

### CODE REVIEW

**Comment by ainsleyc** [comment]
Looks good, thanks!

**Comment by dannief** [comment]
Hey @ainsleyc. I just came here looking if this issue was addressed. Seems it was. Great! But I don't think this version is on npm. Can you publish? Thanks.

**Comment by ainsleyc** [comment]
Ah yeah perhaps I forgot to do that, will do it later tonight.

**Comment by ainsleyc** [comment]
Done. Thanks for reminding me!

**Comment by dannief** [comment]
Great. Appreciate it! ... No Problem.

**Pull request merged**
